//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalInstruments.SemiconductorTestLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NationalInstruments.SemiconductorTestLibrary.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested function is not supported by this device: {0}..
        /// </summary>
        internal static string DAQmx_FuncGenNotSupported {
            get {
                return ResourceManager.GetString("DAQmx_FuncGenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} channels to read..
        /// </summary>
        internal static string DAQmx_NoChannelsToRead {
            get {
                return ResourceManager.GetString("DAQmx_NoChannelsToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample clock rate is not the same for all underlying instrument sessions..
        /// </summary>
        internal static string DAQmx_SampleClockRateNotDistinct {
            get {
                return ResourceManager.GetString("DAQmx_SampleClockRateNotDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the sequencer flag ({0}) is not the same for all underlying instrument sessions..
        /// </summary>
        internal static string Digital_SequencerFlagNotDistinct {
            get {
                return ResourceManager.GetString("Digital_SequencerFlagNotDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the sequencer register ({0}) is not the same for all underlying instrument sessions..
        /// </summary>
        internal static string Digital_SequencerRegisterNotDistinct {
            get {
                return ResourceManager.GetString("Digital_SequencerRegisterNotDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDR offsets for following channels are missing from {0}: {1}..
        /// </summary>
        internal static string Digital_TDROffsetsMissing {
            get {
                return ResourceManager.GetString("Digital_TDROffsetsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the time set period ({0}) is not the same for all underlying instrument sessions..
        /// </summary>
        internal static string Digital_TimeSetPeriodNotDistinct {
            get {
                return ResourceManager.GetString("Digital_TimeSetPeriodNotDistinct", resourceCulture);
            }
        }
    }
}
