// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "Use var to simplify code when creating a new class object via constructor, which is just as readable.")]
[assembly: SuppressMessage("Style", "NI1704:Identifiers should be spelled correctly", Justification = "Custom dictionary is not working, so suppress for now.")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Per-instrument per-channel returns can be discarded.", Scope = "member", Target = "~M:Accelerometer.TestSteps.BurstPattern(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[],System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Per-instrument per-channel returns can be discarded.", Scope = "member", Target = "~M:Accelerometer.TestSteps.CheckPartNumberRegisterWithMultipleVccValues(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[],System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Per-instrument per-channel returns can be discarded.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TestIdlePowerConsumption(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Per-instrument per-channel returns can be discarded.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TestLeakage(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[])")]
[assembly: SuppressMessage("Style", "IDE0270:Use coalesce expression", Justification = "Purposefully not using coalesce expression for better readaiblity", Scope = "member", Target = "~M:Accelerometer.TestSteps.SetupVcc(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[])")]
[assembly: SuppressMessage("Style", "IDE0047:Remove unnecessary parentheses", Justification = "Intentially leaving parentheses for easier readaiblity.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TrimVrefValue(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[])")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Leaving for readability.", Scope = "member", Target = "~M:Accelerometer.TestSteps.ConvertDoubleToByte(System.Double)~System.Byte")]
[assembly: SuppressMessage("Style", "IDE0005:Using directive is unnecessary.", Justification = "Leaving as this this intentionaly and used as template.")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "Leaving as this this intentionaly and used for template.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TemplateTestStep(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext)")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.MeasureVref(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String)")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.BurstPattern(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[],System.String,System.String)")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.CheckPartNumberRegisterWithMultipleVccValues(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[],System.String,System.String[])")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.ResetDUTAndSetMode(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String,System.String)")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.ResetPowerSupplyToVccTypical(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[])")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.SetupVcc(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[])")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TemplateTestStep(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext)")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TestIdlePowerConsumption(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String,System.String)")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TrimVrefValue(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String[])")]
[assembly: SuppressMessage("Naming", "VSSpell002:Ignore Word", Justification = "The following words are accpetable: spi, vcc, tsm, vref.", Scope = "member", Target = "~M:Accelerometer.TestSteps.SetupNIScopeForVref(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "Custom dictionary is not working, so suppress for now.")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1122:Use string.Empty for empty strings", Justification = "This is not approprate/best-practice for ni-driver code.", Scope = "member", Target = "~M:Accelerometer.TestSteps.SetupNIScopeForVref(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1122:Use string.Empty for empty strings", Justification = "This is not approprate/best-practice for ni-driver code.", Scope = "member", Target = "~M:Accelerometer.TestSteps.TestIdlePowerConsumption(NationalInstruments.TestStand.SemiconductorModule.CodeModuleAPI.ISemiconductorModuleContext,System.String,System.String)")]
