### YamlMime:ManagedReference
items:
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings
  commentId: T:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings
  id: DCPowerSettings
  parent: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  children:
  - NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.#ctor
  - NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings
  - NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings
  langs:
  - csharp
  - vb
  name: DCPowerSettings
  nameWithType: DCPowerSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings
  type: Class
  source:
    href: https://github.com/ni/semi-test-library-dotnet/blob/0892583e61c40826fb511ac3605e49ef675ddfff/SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/DCPower/Types.cs
  assemblies:
  - NationalInstruments.SemiconductorTestLibrary.Extensions
  namespace: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  summary: Defines DCPower settings.
  example: []
  syntax:
    content: public class DCPowerSettings
    content.vb: Public Class DCPowerSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.#ctor
  commentId: M:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.#ctor
  id: '#ctor'
  parent: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings
  langs:
  - csharp
  - vb
  name: DCPowerSettings()
  nameWithType: DCPowerSettings.DCPowerSettings()
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.DCPowerSettings()
  type: Constructor
  source:
    href: https://github.com/ni/semi-test-library-dotnet/blob/0892583e61c40826fb511ac3605e49ef675ddfff/SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/DCPower/Types.cs
  assemblies:
  - NationalInstruments.SemiconductorTestLibrary.Extensions
  namespace: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  summary: Default constructor.
  example: []
  syntax:
    content: public DCPowerSettings()
    content.vb: Public Sub New()
  overload: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.#ctor*
  nameWithType.vb: DCPowerSettings.New()
  fullName.vb: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.New()
  name.vb: New()
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings
  commentId: P:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings
  id: SourceSettings
  parent: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings
  langs:
  - csharp
  - vb
  name: SourceSettings
  nameWithType: DCPowerSettings.SourceSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings
  type: Property
  source:
    href: https://github.com/ni/semi-test-library-dotnet/blob/0892583e61c40826fb511ac3605e49ef675ddfff/SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/DCPower/Types.cs
  assemblies:
  - NationalInstruments.SemiconductorTestLibrary.Extensions
  namespace: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  summary: The source settings.
  example: []
  syntax:
    content: public DCPowerSourceSettings SourceSettings { get; set; }
    parameters: []
    return:
      type: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSourceSettings
    content.vb: Public Property SourceSettings As DCPowerSourceSettings
  overload: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings*
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings
  commentId: P:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings
  id: MeasureSettings
  parent: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings
  langs:
  - csharp
  - vb
  name: MeasureSettings
  nameWithType: DCPowerSettings.MeasureSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings
  type: Property
  source:
    href: https://github.com/ni/semi-test-library-dotnet/blob/0892583e61c40826fb511ac3605e49ef675ddfff/SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/DCPower/Types.cs
  assemblies:
  - NationalInstruments.SemiconductorTestLibrary.Extensions
  namespace: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  summary: The measure settings.
  example: []
  syntax:
    content: public DCPowerMeasureSettings MeasureSettings { get; set; }
    parameters: []
    return:
      type: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerMeasureSettings
    content.vb: Public Property MeasureSettings As DCPowerMeasureSettings
  overload: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings*
references:
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  commentId: N:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  isExternal: true
  href: NationalInstruments.html
  name: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  nameWithType: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  spec.csharp:
  - uid: NationalInstruments
    name: NationalInstruments
    isExternal: true
    href: NationalInstruments.html
  - name: .
  - uid: NationalInstruments.SemiconductorTestLibrary
    name: SemiconductorTestLibrary
    isExternal: true
    href: NationalInstruments.SemiconductorTestLibrary.html
  - name: .
  - uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction
    name: InstrumentAbstraction
    isExternal: true
    href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.html
  - name: .
  - uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
    name: DCPower
    isExternal: true
    href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.html
  spec.vb:
  - uid: NationalInstruments
    name: NationalInstruments
    isExternal: true
    href: NationalInstruments.html
  - name: .
  - uid: NationalInstruments.SemiconductorTestLibrary
    name: SemiconductorTestLibrary
    isExternal: true
    href: NationalInstruments.SemiconductorTestLibrary.html
  - name: .
  - uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction
    name: InstrumentAbstraction
    isExternal: true
    href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.html
  - name: .
  - uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
    name: DCPower
    isExternal: true
    href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.#ctor*
  commentId: Overload:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.#ctor
  isExternal: true
  href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.-ctor.html#NationalInstruments_SemiconductorTestLibrary_InstrumentAbstraction_DCPower_DCPowerSettings__ctor
  name: DCPowerSettings
  nameWithType: DCPowerSettings.DCPowerSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.DCPowerSettings
  nameWithType.vb: DCPowerSettings.New
  fullName.vb: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.New
  name.vb: New
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings*
  commentId: Overload:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings
  isExternal: true
  href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings.html#NationalInstruments_SemiconductorTestLibrary_InstrumentAbstraction_DCPower_DCPowerSettings_SourceSettings
  name: SourceSettings
  nameWithType: DCPowerSettings.SourceSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.SourceSettings
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSourceSettings
  commentId: T:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSourceSettings
  parent: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  isExternal: true
  href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSourceSettings.html
  name: DCPowerSourceSettings
  nameWithType: DCPowerSourceSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSourceSettings
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings*
  commentId: Overload:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings
  isExternal: true
  href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings.html#NationalInstruments_SemiconductorTestLibrary_InstrumentAbstraction_DCPower_DCPowerSettings_MeasureSettings
  name: MeasureSettings
  nameWithType: DCPowerSettings.MeasureSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerSettings.MeasureSettings
- uid: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerMeasureSettings
  commentId: T:NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerMeasureSettings
  parent: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower
  isExternal: true
  href: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerMeasureSettings.html
  name: DCPowerMeasureSettings
  nameWithType: DCPowerMeasureSettings
  fullName: NationalInstruments.SemiconductorTestLibrary.InstrumentAbstraction.DCPower.DCPowerMeasureSettings
memberLayout: SeparatePages
